[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'yyatsuo/vimrc'

[[plugins]]
repo = 'Shougo/vimproc.vim'
hook_post_update = '''
  let g:dein#plugin.build = 'make'
'''
[[plugins]]
repo = 'altercation/vim-colors-solarized'
